server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:your_password_here}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false

logging:
  level:
    com.bookstore: INFO
    org.springframework.security: WARN
    root: WARN

# Production JWT Configuration
jwt:
  secret: ${JWT_SECRET:please-change-this-secret-in-production}
  expiration: ${JWT_EXPIRATION:3600000} # 1 hour in production